// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVF2Gcza9CwldHyO-eRlAMTRP2zfmDQ_0',
    appId: '1:1069693169424:web:4abdad49dd78ae52bc7f95',
    messagingSenderId: '1069693169424',
    projectId: 'pks14-550f4',
    authDomain: 'pks14-550f4.firebaseapp.com',
    storageBucket: 'pks14-550f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbF7rj7ZtPaHLzFrMkbhKGlYufGf3p4r4',
    appId: '1:1069693169424:android:568d7bd1e0a0b65ebc7f95',
    messagingSenderId: '1069693169424',
    projectId: 'pks14-550f4',
    storageBucket: 'pks14-550f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RsX-z49NO0vzoqa--Esskp9AByW_BI4',
    appId: '1:1069693169424:ios:4a625608332361d5bc7f95',
    messagingSenderId: '1069693169424',
    projectId: 'pks14-550f4',
    storageBucket: 'pks14-550f4.firebasestorage.app',
    iosBundleId: 'com.example.pks14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RsX-z49NO0vzoqa--Esskp9AByW_BI4',
    appId: '1:1069693169424:ios:4a625608332361d5bc7f95',
    messagingSenderId: '1069693169424',
    projectId: 'pks14-550f4',
    storageBucket: 'pks14-550f4.firebasestorage.app',
    iosBundleId: 'com.example.pks14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVF2Gcza9CwldHyO-eRlAMTRP2zfmDQ_0',
    appId: '1:1069693169424:web:1f2b93e9b2640626bc7f95',
    messagingSenderId: '1069693169424',
    projectId: 'pks14-550f4',
    authDomain: 'pks14-550f4.firebaseapp.com',
    storageBucket: 'pks14-550f4.firebasestorage.app',
  );
}
